# Generated by Django 3.2.9 on 2021-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211127_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsbaSuggestedPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'csba_suggested_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsBreadth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cs_breadth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsbsSuggestedPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'csbs_suggested_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cs_depth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cs_technical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsbsSuggestedPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dsbs_suggested_plan',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='greeting',
            table='hello_greeting',
        ),
    ]
